# 第十二章 通过异常处理错误

### 一 捕获异常

#### 1. try 块

将所有动作放在 try 块里，然后只需在一个地方就可以捕获所有异常。

#### 2. 异常处理程序

catch，紧跟在 try 块之后。是处理抛出的异常的“地方”。

#### 3. 终止与恢复

### 二 创建自定义异常

必须从已有的异常类继承。

- 让编译器产生默认构造器。
- 自定义接受参数的构造器。

```
e.printStackTrace(System.out) // 打印“从方法调用直到异常抛出处”的方法调用序列
```

#### 异常说明

如 throws Exception, 紧跟在形式参数列表后，属于方法声明的一部分。

用来告知客户端程序员某个方法可能会抛出的异常类型，以便进行相应的处理。

#### 异常与记录日志

```
class LoggingException extends Exception {
	// Logger.getLogger()方法创建了一个 String参数相关联的Logger对象
	// 这个对象会将其输出发送到 System.err
    private static Logger logger = Logger.getLogger("LoggingException");	
    public LoggingException() {
        StringWriter trace = new StringWriter();
        printStackTrace(new PrintWriter(trace));
        // 向 Logger 写入
        logger.severe(trace.toString());
    }
}
```

### 三 捕获所有异常

用基类 Exception 可以捕获所有异常。可以调用它从基类 Throwable 继承的方法来获取详细信息：

```
String getMessage()

String getLocalizedMessage()
```

返回对 Throwable 的简单描述：	

```
String toString()
```

打印 Thowable 和 Thowable 的调用栈轨迹：

```
void printStackTrace()

void printStackTrace(PrintStream)

void printStackTrace(java.io.PrintWriter)
```

调用栈显示了“把你带到异常抛出点”的方法调用序列。其中第一种输出到标准错误，后两种允许选择要输出的流。

在 Thowable 对象的内部记录栈帧的当前状态：

```
Thowable fillInStackTrace()
```

也可以使用 Thowable 从基类 Object 继承的方法：

```
getClass()			// 返回一个表示此对象类型的对象
getName()			// 查询这个 Class 对象包含包信息的名称
getSimpleName()		// 只产生类名称
```

#### 栈轨迹

printStackTrace() 方法提供的信息可通过 getStackTrace() 方法来直接访问。这个方法将返回由栈轨迹中的元素所构成的数组，每一个元素都表示栈中的一帧。元素0是栈顶元素，也是调用序列中的最后一个方法调用（这个 Thowable 被创建和抛出之处）。

#### 异常链

即，在捕获一个异常后抛出另一个异常，并希望保存原始异常的信息。

Thowable 的子类在构造器中接受一个 cause 对象作为参数，cause 表示原始异常。

在 Thowable 的子类中，只有 Error、Exception、RuntimeException 提供了带 cause 参数的构造器。要把其他类型的异常链起来，应该使用 initCause() 方法而不是构造器。

### 四 Java 标准异常

Thowable 类被用来表示任何可以作为异常被抛出的类。Thowable 对象可分为两种类型：

1. Error 用来表示编译时和系统错误

2. Exception 是可以被抛出的基本类型，在 Java 类库、用户方法以及运行时故障中都可能抛出。

   是我们应该关心的异常。

**特例：RuntimeException**

不受检查异常。运行时异常都是从 RuntimeException 继承而来。不必在异常说明中列出。

RuntimeException代表的是编程错误：

1. 无法预料的错误。（比如在控制范围以外传进来的 null 引用）
2. 作为程序员，应该在代码中进行检查的错误。（比如数组越界）

### 五 使用 finally 进行清理

无论 try 块中的异常是否抛出，都能得到执行的代码。通常适用于内存回收之外的情况。

应用：

将 try 块放进 while 循环语句里，就能够回到异常抛出的地点。还可以加 static 类型的计数器，在循环在放弃之前尝试一定的次数。

**finally 用来做什么：**

当要把内存之外的资源恢复到它们的初始状态时，如已经打开的文件或网络连接、屏幕上画的图形、关闭开关等；

在 finally 内部，方法从何处 return 无关紧要。

**异常丢失：**

用某些特殊的方式使用 finally 子句，如 finally 中抛出新异常取代前一个异常，或者 finally 中直接 return.

**清理惯用法：**

对于在构造阶段可能会抛出异常，并且要求清理的类，最安全的方式是使用嵌套的 try 子句；

这种方法在构造器不抛出异常时也应该运用。基本规则是：

在创建需要清理的对象后，立即进入一个 try-finally 语句块。

### 六 异常的限制

- 当覆盖方法的时候，只能抛出在基类方法的异常说明里列出的那些异常；派生类方法也可以不抛出任何异常，即使它是基类所定义的异常。
- 异常限制对构造器不起作用。子类构造器可以抛出基类没有的异常，但是子类构造器的异常说明必须包含基类构造器的异常说明。
- 派生类构造器不能捕获基类构造器抛出的异常。

### 七 异常匹配

**把“被检查的异常”转换为“不检查的异常”**

当不知道如何处理这个异常，但又不想把它“吞了”时，可以把“被检查的异常”包装进 RuntimeException 里。

这样还可以 用 getCause() 捕获并处理特定的异常，比如用 switch 语句。
